// Generated by CoffeeScript 1.12.7
(function() {
  var addSymmetricProps, camera, clock, controls, directionalLight, loader, mouse, objects, projector, raycaster, render, renderer, scene, selection, selectionMaterial, selectionMesh;

  camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);

  renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: true
  });

  scene = new THREE.Scene();

  clock = new THREE.Clock();

  mouse = new THREE.Vector2();

  objects = [];

  selection = null;

  selectionMesh = null;

  selectionMaterial = new THREE.MeshBasicMaterial({
    color: 0xff0000,
    side: THREE.BackSide
  });

  raycaster = new THREE.Raycaster();

  projector = new THREE.Projector();

  renderer.setPixelRatio(window.devicePixelRatio);

  renderer.setSize(window.innerWidth, window.innerHeight);

  renderer.setClearColor(0x3d3d3d, 1.0);

  renderer.shadowMap.enabled = true;

  renderer.shadowMap.type = THREE.PCFShadowMap;

  $('#editor').append(renderer.domElement);

  camera.position.z = 15;

  camera.lookAt(new THREE.Vector3(0, 0, 0));

  scene.add(camera);

  controls = new THREE.OrbitControls(camera, renderer.domElement);

  controls.enableZoom = true;

  controls.addEventListener('change', function() {
    return render;
  });

  directionalLight = new THREE.DirectionalLight(0xffffff, 1, 100);

  directionalLight.position.set(1, 1, 1);

  directionalLight.castShadow = true;

  scene.add(directionalLight);

  loader = new THREE.STLLoader();

  loader.crossOrigin = '';

  loader.load("models/core.stl", function(geometry) {
    var group, mat;
    mat = new THREE.MeshStandardMaterial({
      color: 0xfcde00
    });
    group = new THREE.Mesh(geometry, mat);
    group.rotation.x = -0.5 * Math.PI;
    group.rotation.z = Math.PI / 6;
    group.scale.set(0.1, 0.1, 0.1);
    scene.add(group);
    objects.push(group);
    return group.position.set(0, 1, 0);
  });

  render = function() {
    requestAnimationFrame(render);
    return renderer.render(scene, camera);
  };

  render();

  document.getElementById('add4props').addEventListener("mousedown", function(event) {
    addSymmetricProps(2, 0, 60);
    addSymmetricProps(1, 60);
    return addSymmetricProps(1, 240);
  });

  document.getElementById('add3props').addEventListener("mousedown", function(event) {
    return addSymmetricProps(3);
  });

  document.getElementById('add6props').addEventListener("mousedown", function(event) {
    return addSymmetricProps(6);
  });

  addSymmetricProps = function(num, offset, rotateTo) {
    if (offset == null) {
      offset = 0;
    }
    if (rotateTo == null) {
      rotateTo = 0;
    }
    return loader.load("models/prop.stl", function(geometry) {
      var group, i, mat, pivot, results;
      mat = new THREE.MeshStandardMaterial({
        color: 0xfcde00
      });
      i = 1;
      results = [];
      while (i <= num) {
        group = new THREE.Mesh(geometry, mat);
        group.scale.set(0.1, 0.1, 0.1);
        group.rotation.x = -0.5 * Math.PI;
        group.rotation.z = Math.PI / 6 + rotateTo * Math.PI / 180;
        group.position.set(16.5, 1, 0);
        pivot = new THREE.Object3D();
        pivot.add(group);
        pivot.rotation.y = (360 / num + offset) / 180 * Math.PI * i++;
        results.push(scene.add(pivot));
      }
      return results;
    });
  };

  renderer.domElement.addEventListener('mousedown', function(event) {
    var intersects;
    event.preventDefault();
    mouse.x = event.clientX / renderer.domElement.clientWidth * 2 - 1;
    mouse.y = -(event.clientY / renderer.domElement.clientHeight) * 2 + 1;
    raycaster.setFromCamera(mouse, camera);
    intersects = raycaster.intersectObjects(objects);
    console.log(objects);
    console.log(intersects);
    if (intersects.length > 0) {
      selection = intersects[0].object;
      selectionMesh = new THREE.Mesh(selection.geometry, selectionMaterial);
      selectionMesh.position = selection.position;
      selectionMesh.scale.multiplyScalar(1.05);
      return selection.add(selectionMesh);
    } else {
      if (selection !== null) {
        selection.remove(selectionMesh);
        return selection = null;
      }
    }
  });

}).call(this);
